# Generated by Django 4.2 on 2023-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictureurl',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/data-qc-api.appspot.com/o/profiles%2FQC_logo.jpeg?alt=media&token=a8577eee-215a-4b33-9b61-7c764a4eb171'),
        ),
    ]
