# Generated by Django 4.2 on 2023-08-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsmtto', models.JSONField()),
                ('questionviews', models.JSONField()),
                ('questionsdeterioration', models.JSONField()),
                ('tankidentification', models.JSONField()),
                ('observationsandresults', models.JSONField()),
                ('signatures', models.JSONField()),
                ('status', models.IntegerField(choices=[(1, 'Espera'), (2, 'Rechazado'), (3, 'Aprobado')], default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.companie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.user')),
                ('userCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.usercompany')),
            ],
        ),
    ]
