# Generated by Django 4.2 on 2023-04-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_users_user'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsmtto', models.JSONField()),
                ('questionviews', models.JSONField()),
                ('questionsdeterioration', models.JSONField()),
                ('technicalId', models.IntegerField()),
                ('companieId', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Espera'), (2, 'Rechazado'), (3, 'Aprobado')], default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportscompanie', to='companies.companie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportsuser', to='users.user')),
            ],
        ),
    ]
