# Generated by Django 4.2 on 2023-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photos',
            field=models.JSONField(null=True),
        ),
    ]
