# Generated by Django 4.2 on 2024-01-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
