# Generated by Django 4.2 on 2023-04-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_rename_users_user'),
        ('reports', '0002_remove_report_companieid_remove_report_technicalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='companie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companie'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
