# Generated by Django 4.2 on 2023-04-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_user'),
        ('companies', '0001_initial'),
        ('reports', '0003_alter_report_companie_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companie', to='companies.companie'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
    ]
