# Generated by Django 4.2 on 2023-08-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_companie_address_remove_companie_manager_and_more'),
        ('reports', '0005_alter_report_companie_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='userCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.usercompany'),
        ),
    ]
