# Generated by Django 4.2 on 2023-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='userCompany',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
