# Generated by Django 4.2 on 2023-09-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='address',
            field=models.CharField(default='Bogota D.C', max_length=200),
        ),
        migrations.AddField(
            model_name='companie',
            name='city',
            field=models.CharField(default='Bogota', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.companie'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
